<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Define the account data based on the provided chart of accounts
        $accounts = [
            // ASET
            ['code' => '1111', 'name' => 'Kas di Rekening Pemerintah di Bank Indonesia dan Bank Umum dalam Rupiah'],
            ['code' => '11111', 'name' => 'Kas di Bank Indonesia dalam Rupiah'],
            ['code' => '111111', 'name' => 'Kas di Rekening KUN dalam Rupiah'],
            ['code' => '111112', 'name' => 'Kas di Rekening Sub RKUN Kuasa BUN Pusat'],
            ['code' => '111113', 'name' => 'Kas di Rekening SAL'],
            ['code' => '111114', 'name' => 'Kas di Rekening Talangan Reksus Kosong'],
            ['code' => '111115', 'name' => 'Kas di Rekening Penempatan dalam Rupiah'],
            ['code' => '111116', 'name' => 'Kas di Rekening Antara Reksus'],
            ['code' => '111117', 'name' => 'Kas di Rekening Khusus dalam Rupiah'],
            ['code' => '111118', 'name' => 'Kas di Rekening Sub BUN Talangan'],
            ['code' => '111119', 'name' => 'Kas di Rekening Penampungan Pendapatan Rekening Pembangunan Hutan'],
            ['code' => '11112', 'name' => 'Kas di Rekening Sub RKUN'],
            ['code' => '111121', 'name' => 'Kas di Rekening Sub RKUN Penerimaan'],
            ['code' => '111122', 'name' => 'Kas di Rekening Sub RKUN Pengeluaran'],
            ['code' => '111123', 'name' => 'Kas di Rekening Penerimaan Penyetoran Retur SP2D dalam Rupiah'],
            ['code' => '11113', 'name' => 'Kas di Rekening Surat Utang Negara'],
            ['code' => '111131', 'name' => 'Kas di Rekening Penerimaan Surat Utang Negara'],
            ['code' => '111132', 'name' => 'Kas di Rekening Pengeluaran Surat Utang Negara'],
            ['code' => '11114', 'name' => 'Kas di Rekening Persepsi Pusat'],
            ['code' => '111141', 'name' => 'Kas di Rekening Persepsi Pusat'],
            ['code' => '111142', 'name' => 'Kas di Rekening Pos Persepsi Pusat'],
            ['code' => '11115', 'name' => 'Kas di Rekening Pengeluaran Kuasa BUN Pusat-SPAN'],
            ['code' => '111151', 'name' => 'Kas di Rekening Pengeluaran Kuasa BUN Pusat SPAN Non Gaji'],
            ['code' => '111152', 'name' => 'Kas di Rekening Pengeluaran Kuasa BUN Pusat SPAN - Gaji'],
            ['code' => '1112', 'name' => 'Kas di Rekening Pemerintah di Bank Indonesia dan Bank Umum dalam Valuta Asing'],
            ['code' => '11121', 'name' => 'Kas di Bank Indonesia dalam Valuta Asing'],
            ['code' => '111211', 'name' => 'Kas di Rekening KUN dalam Valuta USD'],
            ['code' => '111212', 'name' => 'Kas di Rekening Giro Kas Negara Dalam Valuta Asing'],
            ['code' => '111213', 'name' => 'Kas di Rekening Hasil Minyak Perjanjian Karya'],
            ['code' => '111214', 'name' => 'Kas di Rekening Khusus dalam Valuta Asing'],
            ['code' => '111215', 'name' => 'Kas di Rekening Penempatan dalam Valuta USD'],
            ['code' => '111216', 'name' => 'Kas di Rekening KUN Dalam Valuta Yen'],
            ['code' => '111217', 'name' => 'Kas di Rekening Penempatan Dalam Valuta Yen'],
            ['code' => '111218', 'name' => 'Kas di Rekening KUN dalam Valuta Euro'],
            ['code' => '111219', 'name' => 'Kas di Rekening Penempatan Dalam Valuta Euro'],
            ['code' => '11122', 'name' => 'Kas di Rekening Penerimaan Penyetoran Retur SP2D dalam Valuta Asing'],
            ['code' => '111221', 'name' => 'Kas di Rekening Penerimaan Penyetoran Retur SP2D dalam Valuta Asing JPY'],
            ['code' => '111222', 'name' => 'Kas di Rekening Penerimaan Penyetoran Retur SP2D dalam Valuta Asing USD'],
            ['code' => '111223', 'name' => 'Kas di Rekening Penerimaan Penyetoran Retur SP2D dalam Valuta Asing Euro'],
            ['code' => '11123', 'name' => 'Kas di Rekening Pengeluaran Kuasa BUN Pusat SPAN dalam Valas'],
            ['code' => '111231', 'name' => 'Kas di Rekening Pengeluaran Kuasa BUN Pusat SPAN dalam Valas USD Non Gaji'],
            ['code' => '111232', 'name' => 'Kas di Rekening Pengeluaran Kuasa BUN Pusat SPAN dalam Valas Euro Non Gaji'],
            ['code' => '1113', 'name' => 'Kas di Rekening Pemerintah Lainnya'],
            ['code' => '11131', 'name' => 'Kas di Rekening Pemerintah Lainnya di Bank Indonesia'],
            ['code' => '111311', 'name' => 'Kas Pemerintah Lainnya dalam Rupiah'],
            ['code' => '111312', 'name' => 'Kas di Rekening Pemerintah Lainnya dalam Valuta Asing'],
            ['code' => '111313', 'name' => 'Kas di Rekening Penerimaan - Dana Investasi'],
            ['code' => '111314', 'name' => 'Kas di Rekening Penerimaan Dana Pembangunan Daerah'],
            ['code' => '111315', 'name' => 'Kas di Rekening Penerimaan Migas - RPL'],
            ['code' => '111316', 'name' => 'Kas di Rekening Penerimaan Panas Bumi pada Kuasa BUN Pusat'],
            ['code' => '111317', 'name' => 'Kas di Rekening Pertambangan dan Perikanan pada Kuasa BUN Pusat'],
            ['code' => '111318', 'name' => 'Kas di Rekening Kelolaan Treasury Dealing Room'],
            ['code' => '111319', 'name' => 'Kas di Rekening Penerbitan Surat Berharga Negara'],
            ['code' => '11132', 'name' => 'Kas di Rekening Pemerintah Lainnya di Bank Umum'],
            ['code' => '111321', 'name' => 'Kas di Rekening Pengeluaran Kuasa BUN Pusat'],
            ['code' => '111322', 'name' => 'Kas Pemerintah yang ada di K/L'],
            ['code' => '111323', 'name' => 'Kas Pemerintah yang ada di BLU'],
            ['code' => '111324', 'name' => 'Kas di Rekening PFK'],
            ['code' => '111325', 'name' => 'Kas di Rekening Pemerintah di Bank Umum Dalam Rangka Penempatan'],
            ['code' => '111326', 'name' => 'Kas di Rekening Pemerintah di Bank Umum Dalam Rangka Hibah Luar Negeri Bencana Alam'],
            ['code' => '111327', 'name' => 'Kas di Rekening PHLN'],
            ['code' => '111328', 'name' => 'Kas di Rekening Dana Bergulir'],
            ['code' => '111329', 'name' => 'Kas lainnya'],
            ['code' => '11134', 'name' => 'Kas di Rekening Retur Kuasa BUN'],
            ['code' => '111341', 'name' => 'Kas di Rekening Retur Kuasa BUN Pusat SPAN-Non Gaji'],
            ['code' => '111342', 'name' => 'Kas di Rekening Retur Kuasa BUN Pusat SPAN-Gaji'],
            ['code' => '111343', 'name' => 'Kas di Rekening Retur Reksus Pinjaman/Hibah/Surat Berharga Syariah Negara'],
            ['code' => '1114', 'name' => 'Kas di Rekening Kas di KPPN'],
            ['code' => '11141', 'name' => 'Kas di Bank Indonesia'],
            ['code' => '111411', 'name' => 'Kas di Rekening Pengeluaran di Bank Tunggal'],
            ['code' => '111412', 'name' => 'Kas di Rekening Pengeluaran BI dalam Rupiah'],
            ['code' => '11142', 'name' => 'Kas di Bank Umum'],
            ['code' => '111421', 'name' => 'Kas di Rekening Pengeluaran di Bank Operasional'],
            ['code' => '111422', 'name' => 'Kas di Rekening Penerimaan (Persepsi/Devisa Persepsi)'],
            ['code' => '111423', 'name' => 'Kas di Rekening Retur BO/Pos (KPPN)'],
            ['code' => '11143', 'name' => 'Kas KPPN di Bank Indonesia dalam Valuta Asing'],
            ['code' => '111431', 'name' => 'Kas di Rekening Pengeluaran Bl dalam Valuta USD'],
            ['code' => '111432', 'name' => 'Kas di Rekening Pengeluaran Bi dalam Valuta Yen'],
            ['code' => '111433', 'name' => 'Kas di Rekening Pengeluaran BI dalam Valuta Euro'],
            ['code' => '11144', 'name' => 'Kas KPPN di Bank Umum dalam Valuta Asing'],
            ['code' => '111441', 'name' => 'Kas di Rekening Penerimaan (Persepsi/Devisa Persepsi) dalam Valuta USD'],
            ['code' => '11145', 'name' => 'Kas di Rekening Retur BI dalam Rupiah'],
            ['code' => '111451', 'name' => 'Kas di Rekening Retur BI dalam Rupiah'],
            ['code' => '11146', 'name' => 'Kas di Rekening Retur BI dalam Valuta Asing'],
            ['code' => '111461', 'name' => 'Kas di Rekening Retur BI dalam Valuta USD'],
            ['code' => '111462', 'name' => 'Kas di Rekening Retur BI dalam Valuta Yen'],
            ['code' => '111463', 'name' => 'Kas di Rekening Retur BI dalam Valuta Euro'],
            ['code' => '111469', 'name' => 'Kas di Rekening Retur BI dalam Valuta Asing Lainnya'],
            ['code' => '1115', 'name' => 'Kas dalam Transito'],
            ['code' => '11151', 'name' => 'Kas dalam Transito BUN'],
            ['code' => '111511', 'name' => 'Kas dalam Transito BUN'],
            ['code' => '111512', 'name' => 'Kas dalam Transito Rekening Pinjaman/Hibah'],
            ['code' => '111513', 'name' => 'Kas dalam Transito TUP'],
            ['code' => '111514', 'name' => 'Kas dalam Transito UP'],
            ['code' => '111515', 'name' => 'Kas dalam Transito BLU'],
            ['code' => '111516', 'name' => 'Kas dalam Transito-Transaksi Non Kas'],
            ['code' => '111517', 'name' => 'Kas dalam Transito-Transaksi DTP'],
            ['code' => '111519', 'name' => 'Kas dalam Transito Lainnya'],
            ['code' => '11152', 'name' => 'Kas dalam Transito - K/L'],
            ['code' => '111521', 'name' => 'Kas dalam Transito Perwakilan Luar Negeri'],
            ['code' => '1116', 'name' => 'Kas di Bendahara Pengeluaran'],
            ['code' => '11161', 'name' => 'Kas di Bendahara Pengeluaran'],
            ['code' => '111611', 'name' => 'Kas di Bendahara Pengeluaran'],
            ['code' => '111613', 'name' => 'Kas di Bendahara Pengeluaran TUP'],
            ['code' => '1117', 'name' => 'Kas di Bendahara Penerimaan'],
            ['code' => '11171', 'name' => 'Kas di Bendahara Penerimaan'],
            ['code' => '111711', 'name' => 'Kas di Bendahara Penerimaan'],
            ['code' => '1118', 'name' => 'Kas Lainnya dan Setara Kas'],
            ['code' => '11181', 'name' => 'Setara Kas'],
            ['code' => '111811', 'name' => 'Surat Berharga'],
            ['code' => '111812', 'name' => 'Penempatan di Bank Umum'],
            ['code' => '111813', 'name' => 'Reverse Repo'],
            ['code' => '111814', 'name' => 'Foreign Exchange'],
            ['code' => '111819', 'name' => 'Setara Kas lainnya'],
            ['code' => '11182', 'name' => 'Kas Lainnya Pada Kementerian Negara/Lembaga'],
            ['code' => '111821', 'name' => 'Kas Lainnya di Bendahara Pengeluaran'],
            ['code' => '111822', 'name' => 'Kas Lainnya di Kementerian Negara/Lembaga dari Hibah'],
            ['code' => '111823', 'name' => 'Kas Lainnya di K/L Dana Kelolaan LPP RRI/TVRI'],
            ['code' => '111824', 'name' => 'Kas Lainnya dari Reklasifikasi Kas Besi'],
            ['code' => '111825', 'name' => 'Kas Lainnya di Bendahara Penerimaan'],
            ['code' => '111826', 'name' => 'Kas Lainnya di BLU'],
            ['code' => '111827', 'name' => 'Kas Lainnya di K/L dari Hibah yang Belum Disahkan'],
            ['code' => '1119', 'name' => 'Kas pada Badan Layanan Umum'],
            ['code' => '11191', 'name' => 'Kas - BLU'],
            ['code' => '111911', 'name' => 'Kas dan Bank - BLU'],
            ['code' => '111912', 'name' => 'Dana yang akan Dijaminkan BLU'],
            ['code' => '111913', 'name' => 'Dana yang akan Dipadankan BLU'],
            ['code' => '111914', 'name' => 'Kas dan Bank BLU Belum Disahkan'],
            ['code' => '11192', 'name' => 'Setara Kas BLU'],
            ['code' => '111921', 'name' => 'Surat Berharga BLU'],
            ['code' => '111929', 'name' => 'Setara kas Lainnya - BLU'],
            ['code' => '1121', 'name' => 'Uang Muka Dari Rekening KUN'],
            ['code' => '11211', 'name' => 'Uang Muka KUN UP'],
            ['code' => '112111', 'name' => 'Uang Muka KUN UP - PP'],
            ['code' => '1122', 'name' => 'Uang Muka Dari Rekening Khusus'],
            ['code' => '11221', 'name' => 'Uang Muka Reksus UP'],
            ['code' => '112211', 'name' => 'Uang Muka Reksus UP PP Reksus'],
            ['code' => '11222', 'name' => 'Uang Muka Reksus Non UP'],
            ['code' => '112221', 'name' => 'Uang Muka Reksus Kosong'],
            ['code' => '1123', 'name' => 'Talangan kepada RKUN'],
            ['code' => '11231', 'name' => 'Talangan kepada RKUN'],
            ['code' => '112311', 'name' => 'Talangan Dana Cadangan Subsidi kepada RKUN'],
            ['code' => '112312', 'name' => 'Talangan Dana Cadangan DBH kepada RKUN'],
            ['code' => '112313', 'name' => 'Talangan Dana Cadangan PMN kepada RKUN'],
            ['code' => '1131', 'name' => 'Investasi dalam Deposito'],
            ['code' => '11311', 'name' => 'Investasi dalam Deposito'],
            ['code' => '113111', 'name' => 'Investasi dalam Deposito Jangka Pendek'],
            ['code' => '1132', 'name' => 'Investasi dalam Surat Perbendaharaan Negara'],
            ['code' => '11321', 'name' => 'Investasi dalam Surat Perbendaharaan Negara'],
            ['code' => '113211', 'name' => 'Investasi dalam Surat Perbendaharaan Negara'],
            ['code' => '11322', 'name' => 'Investasi Jangka Pendek pada Surat Berharga Negara'],
            ['code' => '113221', 'name' => 'Investasi Jangka Pendek pada SBN dalam Rangka Stabilisasi Pasar'],
            ['code' => '113222', 'name' => 'Investasi Jangka Pendek pada SBN dalam Rangka Optimalisasi Kas'],
            ['code' => '1133', 'name' => 'Investasi Jangka Pendek- Badan Layanan Umum'],
            ['code' => '11331', 'name' => 'Deposito Jangka Pendek - BLU'],
            ['code' => '113311', 'name' => 'Deposito dan Investasi Jangka Pendek Lainnya dari Kas dan Bank BLU yang Sudah Disahkan'],
            ['code' => '113319', 'name' => 'Deposito dan Investasi Jangka Pendek Lainnya dari Dana Kelolaan BLU dan/atau Kas BLU yang dibatasi Penggunaannya'],
            ['code' => '1134', 'name' => 'Bagian Lancar Investasi Non Permanen'],
            ['code' => '11341', 'name' => 'Bagian Lancar Investasi Non Permanen'],
            ['code' => '113411', 'name' => 'Bagian Lancar Investasi Non Permanen'],
            ['code' => '1139', 'name' => 'Investasi Jangka Pendek Lainnya'],
            ['code' => '11391', 'name' => 'Investasi Jangka Pendek Lainnya'],
            ['code' => '113911', 'name' => 'Investasi Jangka Pendek Lainnya'],
            
            // KEWAJIBAN
            ['code' => '2111', 'name' => 'Utang Perhitungan Fihak Ketiga'],
            ['code' => '21111', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) I'],
            ['code' => '211111', 'name' => 'Utang Dana PFK Iuran Jaminan Kesehatan Pegawai'],
            ['code' => '211112', 'name' => 'Utang Dana PFK Iuran Jaminan Kesehatan Pensiunan PNS dan Pejabat Negara'],
            ['code' => '211113', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Beras Bulog'],
            ['code' => '211114', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) 8% Gaji'],
            ['code' => '211115', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Tabungan Wajib Perumahan'],
            ['code' => '211116', 'name' => 'Utang Dana PFK luran Jaminan Kesehatan Pensiunan Prajurit TNI/PNS Kemhan dan Anggota Polri/PNS Polri'],
            ['code' => '211117', 'name' => 'Utang Dana PFK Juran Jaminan Kesehatan dari Pemerintah selaku Pemberi Kerja'],
            ['code' => '211118', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) 2% Asuransi Kesehatan Bidan/Dokter PTT'],
            ['code' => '211119', 'name' => 'Utang Dana PFK Tunggakan Kewajiban luran Jaminan Kesehatan'],
            ['code' => '21112', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Lainnya'],
            ['code' => '211121', 'name' => 'Utang Dana PFK luran Jaminan Kesehatan bagi Anggota Keluarga yang Lain'],
            ['code' => '211122', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Penutupan Rekening'],
            ['code' => '211123', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga Wesel Pemerintah'],
            ['code' => '21115', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) II'],
            ['code' => '211151', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) 8% Gaji TNI/PNS Kemhan dan Polri/PNS Polri'],
            ['code' => '211152', 'name' => 'Utang Dana PFK Simpanan Peserta Tapera bagian Pekerja Pemerintah Pusat'],
            ['code' => '211153', 'name' => 'Utang Dana PFK Simpanan Peserta Tapera bagian Pekerja Pemerintah Daerah'],
            ['code' => '211154', 'name' => 'Utang Dana PFK Simpanan Peserta Tapera bagian Pemberi Kerja Pemerintah Daerah'],
            ['code' => '211155', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) kepada Pusku Kemhan'],
            ['code' => '211156', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Penyaluran Beras BULOG'],
            ['code' => '21116', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga PFK Setoran Pajak Rokok dan Pengalihan Piutang'],
            ['code' => '211161', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Setoran Pajak Rokok'],
            ['code' => '211162', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Pengalihan Piutang'],
            ['code' => '211163', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Hasil Penjualan/Penyelesaian Aset Bekas Milik Eks Bank Dalam Likuidasi'],
            ['code' => '211164', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Pemotongan DAU atau DBH untuk Alokasi Dana Desa (ADD)'],
            ['code' => '211165', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Kontribusi Penerimaan Pajak Rokok untuk mendukung Program Jaminan Kesehatan'],
            ['code' => '211166', 'name' => 'Utang Perwalian/Perhitungan Fihak Ketiga (PFK) Dana Hasil Pemotongan (DHP) untuk Dana Desa'],
            ['code' => '2193', 'name' => 'Uang Muka Rekening Khusus'],
            ['code' => '21931', 'name' => 'Uang Muka Rekening Khusus'],
            ['code' => '219311', 'name' => 'Uang Muka Rekening Khusus'],
            ['code' => '2194', 'name' => 'Uang Muka'],
            ['code' => '21941', 'name' => 'Uang Muka dari KUN'],
            ['code' => '219411', 'name' => 'Uang Muka dari KUN'],
            ['code' => '219412', 'name' => 'Uang Muka dari Kementerian Negara/Lembaga'],
            ['code' => '2195', 'name' => 'Uang Muka dari KPPN'],
            ['code' => '21951', 'name' => 'Uang Muka dari KPPN'],
            ['code' => '219511', 'name' => 'Uang Muka dari KPPN'],
            ['code' => '2197', 'name' => 'Utang Kepada KUN'],
            ['code' => '21971', 'name' => 'Utang Kepada KUN'],
            ['code' => '219711', 'name' => 'Utang Kepada KUN'],
            ['code' => '21972', 'name' => 'Utang Kepada kas BLU'],
            ['code' => '219721', 'name' => 'Utang Kepada kas BLU'],
            ['code' => '2198', 'name' => 'Utang Kepada RPL'],
            ['code' => '21981', 'name' => 'Utang Kepada RPL'],
            ['code' => '219811', 'name' => 'Utang Kepada RPL'],
            ['code' => '21982', 'name' => 'Utang Talangan'],
            ['code' => '219821', 'name' => 'Utang Talangan Dana Cadangan Subsidi'],
            ['code' => '219822', 'name' => 'Utang Talangan Dana Cadangan DBH'],
            ['code' => '219823', 'name' => 'Utang Talangan Dana Cadangan PMN'],

            // EKUITAS
            ['code' => '3111', 'name' => 'SAL'],
            ['code' => '31111', 'name' => 'SAL'],
            ['code' => '311111', 'name' => 'SAL'],
            ['code' => '311112', 'name' => 'Penggunaan SAL'],
            ['code' => '311113', 'name' => 'Penggunaan SAL Earmark'],
            ['code' => '3112', 'name' => 'SILPA'],
            ['code' => '31121', 'name' => 'SILPA'],
            ['code' => '311211', 'name' => 'SILPA'],
            ['code' => '311212', 'name' => 'Koreksi Pendapatan Tahun Anggaran Yang Lalu'],
            ['code' => '311213', 'name' => 'Koreksi Belanja Tahun Anggaran Yang Lalu'],
            ['code' => '311214', 'name' => 'Surplus/Defisit'],
            ['code' => '311215', 'name' => 'Pembiayaan Netto'],
            ['code' => '3113', 'name' => 'SAL dan SILPA BLU'],
            ['code' => '31131', 'name' => 'SAL - BLU'],
            ['code' => '311311', 'name' => 'SAL - BLU'],
            ['code' => '311312', 'name' => 'Pengembalian Pendapatan BLU Tahun Anggaran Yang Lalu'],
            ['code' => '311313', 'name' => 'SAL Selisih Kurs Belum Terealisasi'],
            ['code' => '311314', 'name' => 'Penggunaan SAL BLU'],
            ['code' => '311315', 'name' => 'Penyesuaian SAL BLU'],
            ['code' => '31132', 'name' => 'SILPA BLU'],
            ['code' => '311321', 'name' => 'SILPA BLU'],
            ['code' => '3117', 'name' => 'Keuntungan/Kerugian yang Belum Terealisasi'],
            ['code' => '31171', 'name' => 'Selisih Kurs'],
            ['code' => '311711', 'name' => 'Selisih Kurs'],
            ['code' => '3119', 'name' => 'Ekuitas Dana Lancar Lainnya'],
            ['code' => '31191', 'name' => 'Ekuitas Dana Lancar Lainnya dari Hibah Langsung'],
            ['code' => '311911', 'name' => 'Ekuitas Dana Lancar Lainnya dari Hibah Langsung'],
            ['code' => '3911', 'name' => 'Ekuitas'],
            ['code' => '39114', 'name' => 'Ekuitas Surplus BLU'],
            ['code' => '391141', 'name' => 'Setoran Surplus BLU'],
            ['code' => '391142', 'name' => 'Transfer Keluar Kas BLU kepada BLU lain'],
            ['code' => '391143', 'name' => 'Transfer Masuk Kas BLU dari BLU lain'],
            ['code' => '3999', 'name' => 'Ekuitas Konsolidasi BUN'],
            ['code' => '39991', 'name' => 'Ekuitas Konsolidasi BUN I'],
            ['code' => '399911', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Akrual dari Kas BP KL'],
            ['code' => '399912', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Akrual dari Kas BLU KL'],
            ['code' => '399913', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Akrual dari Kas Hibah KL'],
            ['code' => '399914', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Kas dari Akun Non Anggaran TAYL'],
            ['code' => '399915', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Kas dari Akun Aset/Kewajiban'],
            ['code' => '399916', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Kas dari Koreksi Kas BUN'],
            ['code' => '399917', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Kas dari Koreksi Kas RPL'],
            ['code' => '399918', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Kas dari Koreksi Kas KPPN'],
            ['code' => '399919', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Kas dari Koreksi Kas BLU'],
            ['code' => '39992', 'name' => 'Ekuitas Konsolidasi BUN II'],
            ['code' => '399921', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Kas dari Koreksi Kas Hibah'],
            ['code' => '399922', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Kas dari Koreksi Kas Transitoris'],
            ['code' => '399923', 'name' => 'Ekuitas Konsolidasi BUN pada Ledger Kas dari Koreksi Kas Escrow'],
            // Add other major sections below
        ];

        // Chunk the data to avoid memory issues with a large number of records
        foreach (array_chunk($accounts, 500) as $chunk) {
            DB::table('accounts')->insert($chunk);
        }
    }
}

